### PR TITLE
Add rust-toolchain and fix core_bound/vectorization_1 loop range

### PR DESCRIPTION
**Pull request by AOx0**
As the title says:
- Adds `./rust-toolchain.toml` so that users no longer need to execute `rustup default nightly`, instead cargo automatically downloads and uses nightly rust when compiling this specific project.  
- Remove Cargo.lock since it contains references to crates' code that no longer compile with the current nightly rust.
- Fix an invalid loop range in core_bound/vectorization_1
  <details><summary>Details</summary>
  <p>
  
  In [`perf-ninja/labs/core_bound/vectorization_1/solution.cpp#L60`](https://github.com/dendibakh/perf-ninja/blob/2fdd01ff3f501b5b97e9c9f563a614f858ff25a9/labs/core_bound/vectorization_1/solution.cpp#L60) the loop is written as:
  ```c++
  for (unsigned row = 1; row <= sequence1.size(); ++row)
  ``` 
   But the implementation at `labs/core_bound/vectorization_1/` in both [`lib.rs:64`](https://github.com/grahamking/perf-ninja-rs/blob/c47e09e4de519c3c8b9d4aee3f369654712dd18c/labs/core_bound/vectorization_1/src/lib.rs#L64) and [`tests.rs:59`](https://github.com/grahamking/perf-ninja-rs/blob/c47e09e4de519c3c8b9d4aee3f369654712dd18c/labs/core_bound/vectorization_1/src/tests.rs#L59) state:
  ```rs
  for row in 1..sequence1.len()
  ```
  Which results in different results for the same data between the Rust implementation and de C++ parent.
  It's a quick fix:
  ```diff
  - for row in 1..sequence1.len()
  + for row in 1..=sequence1.len()
  ```  

  </p>
  </details>

### CODE REVIEW

**Comment by grahamking** [comment]
Thanks for the PR.

> Remove Cargo.lock since it contains references to crates' code that no longer compile with the current nightly rust.

What doesn't build for you? Can you post the error? I have `rustc 1.73.0-nightly (1d56e3a6d 2023-07-22)` and `cargo clean` then `cargo build` succeed.

We shouldn't remove Cargo.lock. Having the exact same version of dependencies ensures people trying the exercises have similar performance results.

**Comment by grahamking** [comment]
Ah actually I see the error now in `ciborium`. A `rustup update` fixes it, will do now.

Could you change you PR to not touch Cargo.lock, then I can merge it? The off by one fix would be nice to have.

**Comment by AOx0** [comment]
Thanks for your time and quick response :D. 

With a fresh clone of the repository, building the workspace from the root of the project with `1.73.0-nightly` does work. 

But if I where to change the current directory to any of the assignments and try to `cargo bench --bench <bench_assignment>` or `cargo test --tests` then I get the following compilation error, which can be fixed by doing `cargo update`, that is, updating the Cargo.lock, discarding the committed version:

```bash
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/ae/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
```

So yeah, an alternative is to commit a `cargo update`, although it may require constant maintainability. I agree with the performance similarities, i can revert the removal of `Cargo.lock` and just do a `cargo update` if you want to.

**Comment by AOx0** [comment]
Oh, just read the response. Ok, I'll leave Cargo.toml as-is.

Edit: I meant Cargo.lock

**Comment by grahamking** [comment]
Here is the `cargo update` commit :https://github.com/grahamking/perf-ninja-rs/commit/a8791f94f76822a33f667dd000dc810e4d7076bc

**Pull request merged**
